// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vanitha_WebApi_Day_2_HandsOn.Models;

namespace Vanitha_WebApi_Day_2_HandsOn.Migrations
{
    [DbContext(typeof(ADM214DBContext))]
    [Migration("20210718181514_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vanitha_WebApi_Day_2_HandsOn.Models.Department", b =>
                {
                    b.Property<int>("DId")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DId")
                        .HasName("PK__Department__AF2DBB995C0BD1CF");

                    b.HasIndex(new[] { "DepartmentName" }, "DNAME_IDX");

                    b.ToTable("DEPARTMENT");
                });

            modelBuilder.Entity("Vanitha_WebApi_Day_2_HandsOn.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int?>("DepartmentDId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("Permanent")
                        .HasColumnType("bit");

                    b.Property<decimal>("Salary")
                        .HasColumnType("money");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Employee__AF2DBB995C0BD1CF");

                    b.HasIndex("DepartmentDId");

                    b.HasIndex(new[] { "Name" }, "ENAME_IDX");

                    b.ToTable("EMPL");
                });

            modelBuilder.Entity("Vanitha_WebApi_Day_2_HandsOn.Models.Employee", b =>
                {
                    b.HasOne("Vanitha_WebApi_Day_2_HandsOn.Models.Department", "Department")
                        .WithMany("EMPLs")
                        .HasForeignKey("DepartmentDId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Vanitha_WebApi_Day_2_HandsOn.Models.Department", b =>
                {
                    b.Navigation("EMPLs");
                });
#pragma warning restore 612, 618
        }
    }
}
